name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2

    - name: Install Node.js dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
